language: perl

perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

before_script:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov Test::Perl::Critic

script:
  - perl Makefile.PL
  - make
  - make test
  - cover -test

after_success:
  - cover -report codecov
